### ISSUE TITLE
no setup.py found

### ISSUE THREAD

**Issue by DanwildfireV2** [Jegarde/RecNet-Login#3]
every time i run the "python -m pip install..." cmd it says no setup.py found and i cant quite figure out what im doing wrong

**Comment by Jegarde** [comment]
That's on me. I forgot to implement the setup file for installation. Until it's fixed, you can go around it by downloading the files on your PC and copying the [`recnetbot`](https://github.com/Jegarde/RecNet-Login/tree/main/recnetlogin) folder on your project's files. It will work the same.
