### ISSUE TITLE
Install fails on Python 3.11.2 on MacOS

### ISSUE THREAD

**Issue by Bobrobot1** [Jegarde/RecNet-Login#5]
The issue seems to be with the aiohttp library, where it fails during build with the error
`aiohttp/_websocket.c:196:12: fatal error: 'longintrepr.h' file not found`

The issue seems to be experienced by other people using the same library, see [here](https://github.com/aio-libs/aiohttp/issues/6600). Try switching dependencies.

**Comment by Jegarde** [comment]
Can you confirm that later aiohttp versions build correctly on MacOS? I am not able to test it at the moment.

**Comment by Bobrobot1** [comment]
I tested both prerelease versions, and the only one I got to work was 4.0.0a0, see https://pypi.org/project/aiohttp/4.0.0a0/

**Comment by Jegarde** [comment]
I updated the dependency, please try installing now.

**Comment by Bobrobot1** [comment]
![image](https://user-images.githubusercontent.com/24487638/222954320-45ee10f0-9814-415f-b2b4-17df31cd9218.png)
aiohttp installed correctly now! Great work, thank you. I have, however, hit another snag, which you can see in the screenshot above.

**Comment by Jegarde** [comment]
The version of aiohttp appears to be unstable. I will be reverting the dependency change. Here are possible solutions for troubleshooting:
- Try `pip install -U aiohttp==3.8.3` if that installs. This worked for someone else facing the same issue.
- Downgrade Python and try installing the package again if your project supports it.
- Use the synchronous version of RecNet-login that uses another HTTP module altogether.

**Comment by Bobrobot1** [comment]
3.8.3 seemed to work for me!

**Comment by Bobrobot1** [comment]
![image](https://user-images.githubusercontent.com/24487638/222989693-db3abf80-bdc1-4196-8a44-79914d7e7c0c.png)
