### ISSUE TITLE
module

### ISSUE THREAD

**Issue by ooflord20002** [Jegarde/RecNet-Login#8]
module 'recnetlogin' has no attribute 'login_to_recnet'

**Comment by Jegarde** [comment]
Hey. RecNet-Login was unfortunately broken by RecNet reCAPTCHA implementation.

Please refer to these methods to get your token:
- https://github.com/zigzatuzoo/Rec-Room-API-Tool-Box/blob/main/BasicTools/RRAutoAuth.py
- The JS script found at the bottom of the readme of this repository.
